package me.tongzhuangzhuang.business.dto;

import java.io.Serializable;
import org.hibernate.validator.constraints.Length;
import me.tongzhuangzhuang.support.model.BaseModel;


/**
 * 
 * @generated by Code Generator v0.1
 * @date Tue May 31 16:05:12 CST 2016
 */
public class CustCustomerBase extends BaseModel<String> implements Serializable {

  private static final long serialVersionUID = 1L;

  /**
   * @field id
   */
  @Length(min = 1, max = 32, message = "ID长度为32")
  private String id;

  /**
   * @field loginName
   */
  @Length(min = 1, max = 32, message = "LOGIN_NAME长度为32")
  private String loginName;

  /**
   * @field password
   */
  @Length(min = 1, max = 32, message = "PASSWORD长度为32")
  private String password;

  /**
   * @field userName
   */
  @Length(min = 1, max = 32, message = "USER_NAME长度为32")
  private String userName;

  /**
   * @field phone
   */
  @Length(min = 1, max = 16, message = "PHONE长度为16")
  private String phone;

  /**
   * @field email
   */
  @Length(min = 1, max = 255, message = "EMAIL长度为255")
  private String email;

  /**
   * @field deleteFlag
   */
  private Byte deleteFlag;

  /**
   * @return id
   */
  public String getId() {
    return id;
  }

  /**
   * @param id
   */
  public void setId(String id) {
    this.id = id;
  }

  /**
   * @return loginName
   */
  public String getLoginName() {
    return loginName;
  }

  /**
   * @param loginName
   */
  public void setLoginName(String loginName) {
    this.loginName = loginName;
  }

  /**
   * @return password
   */
  public String getPassword() {
    return password;
  }

  /**
   * @param password
   */
  public void setPassword(String password) {
    this.password = password;
  }

  /**
   * @return userName
   */
  public String getUserName() {
    return userName;
  }

  /**
   * @param userName
   */
  public void setUserName(String userName) {
    this.userName = userName;
  }

  /**
   * @return phone
   */
  public String getPhone() {
    return phone;
  }

  /**
   * @param phone
   */
  public void setPhone(String phone) {
    this.phone = phone;
  }

  /**
   * @return email
   */
  public String getEmail() {
    return email;
  }

  /**
   * @param email
   */
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   * @return deleteFlag
   */
  public Byte getDeleteFlag() {
    return deleteFlag;
  }

  /**
   * @param deleteFlag
   */
  public void setDeleteFlag(Byte deleteFlag) {
    this.deleteFlag = deleteFlag;
  }

}
