package me.tongzhuangzhuang.business.dto;

import java.io.Serializable;
import org.hibernate.validator.constraints.Length;
import me.tongzhuangzhuang.support.model.BaseModel;

/**
 * 
 * @generated by Code Generator v0.1
 * @date Tue May 31 16:05:13 CST 2016
 */
public class PrdCategory extends BaseModel<String> implements Serializable {

  private static final long serialVersionUID = 1L;

  /**
   * @field id
   */
  @Length(min = 1, max = 32, message = "ID长度为32")
  private String id;

  /**
   * @field categoryName
   */
  @Length(min = 1, max = 64, message = "CATEGORY_NAME长度为64")
  private String categoryName;

  /**
   * @field categoryType
   */
  private Byte categoryType;

  /**
   * @field categoryRate
   */
  private Object categoryRate;

  /**
   * @field deleteFlag
   */
  private Byte deleteFlag;

  /**
   * @return id
   */
  public String getId() {
    return id;
  }

  /**
   * @param id
   */
  public void setId(String id) {
    this.id = id;
  }

  /**
   * @return categoryName
   */
  public String getCategoryName() {
    return categoryName;
  }

  /**
   * @param categoryName
   */
  public void setCategoryName(String categoryName) {
    this.categoryName = categoryName;
  }

  /**
   * @return categoryType
   */
  public Byte getCategoryType() {
    return categoryType;
  }

  /**
   * @param categoryType
   */
  public void setCategoryType(Byte categoryType) {
    this.categoryType = categoryType;
  }

  /**
   * @return categoryRate
   */
  public Object getCategoryRate() {
    return categoryRate;
  }

  /**
   * @param categoryRate
   */
  public void setCategoryRate(Object categoryRate) {
    this.categoryRate = categoryRate;
  }

  /**
   * @return deleteFlag
   */
  public Byte getDeleteFlag() {
    return deleteFlag;
  }

  /**
   * @param deleteFlag
   */
  public void setDeleteFlag(Byte deleteFlag) {
    this.deleteFlag = deleteFlag;
  }

}
