package me.tongzhuangzhuang.business.service;

import java.util.List;

import me.tongzhuangzhuang.business.dto.CustCustomerBase;

/**
 * 
 * @generated by Code Generator v0.1
 * @Tue May 31 16:05:12 CST 2016
 */
public interface CustCustomerBaseService {

  public List<CustCustomerBase> listCustomers();
}
