package me.tongzhuangzhuang.business.biz;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import me.tongzhuangzhuang.business.dao.CustCustomerBaseDao;
import me.tongzhuangzhuang.business.dto.CustCustomerBase;
import me.tongzhuangzhuang.business.entity.TCustCustomerBase;
import me.tongzhuangzhuang.support.biz.CommonBusiness;
import me.tongzhuangzhuang.support.dao.BaseDao;
import me.tongzhuangzhuang.utils.BeanUtils;


/**
 * 
 * @generated by Code Generator v0.1
 * @Tue May 31 16:05:12 CST 2016
 */
@Service
public class CustCustomerBaseBusiness extends CommonBusiness<CustCustomerBase, TCustCustomerBase, String> {

  @Autowired
  private CustCustomerBaseDao custCustomerBaseDao;

  private static Logger logger = LoggerFactory.getLogger(CustCustomerBaseBusiness.class);

  /**
   * dto转换成po 根据实际情况重写此方法增加其他Bean属性的转换
   */
  @Override
  protected TCustCustomerBase toEntity(CustCustomerBase model) {
    TCustCustomerBase entity = new TCustCustomerBase();
    BeanUtils.copy(model, entity);
    return entity;
  }

  /**
   * po转换成dto 根据实际情况重写此方法增加其他Bean属性的转换
   */
  @Override
  protected CustCustomerBase fromEntity(TCustCustomerBase entity) {
    CustCustomerBase model = new CustCustomerBase();
    BeanUtils.copy(entity, model);
    return model;
  }

  /**
   * 为父类CommonBusiness注入Dao
   */
  @Override
  protected BaseDao<TCustCustomerBase> getBaseDao() {
    return custCustomerBaseDao;
  }

  /**
   * 为父类CommonBusiness注入logger
   */
  @Override
  protected Logger getLogger() {
    return logger;
  }

}
