package me.tongzhuangzhuang.business.biz;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import me.tongzhuangzhuang.business.dao.PrdCategoryDao;
import me.tongzhuangzhuang.business.dto.PrdCategory;
import me.tongzhuangzhuang.business.entity.TPrdCategory;
import me.tongzhuangzhuang.support.biz.CommonBusiness;
import me.tongzhuangzhuang.support.dao.BaseDao;
import me.tongzhuangzhuang.utils.BeanUtils;


/**
 * 
 * @generated by Code Generator v0.1
 * @Tue May 31 16:05:13 CST 2016
 */
@Service
public class PrdCategoryBusiness extends CommonBusiness<PrdCategory, TPrdCategory, String> {

  @Autowired
  private PrdCategoryDao prdCategoryDao;

  private static Logger logger = LoggerFactory.getLogger(PrdCategoryBusiness.class);

  /**
   * dto转换成po 根据实际情况重写此方法增加其他Bean属性的转换
   */
  @Override
  protected TPrdCategory toEntity(PrdCategory model) {
    TPrdCategory entity = new TPrdCategory();
    BeanUtils.copy(model, entity);
    return entity;
  }

  /**
   * po转换成dto 根据实际情况重写此方法增加其他Bean属性的转换
   */
  @Override
  protected PrdCategory fromEntity(TPrdCategory entity) {
    PrdCategory model = new PrdCategory();
    BeanUtils.copy(entity, model);
    return model;
  }

  /**
   * 为父类CommonBusiness注入Dao
   */
  @Override
  protected BaseDao<TPrdCategory> getBaseDao() {
    return prdCategoryDao;
  }

  /**
   * 为父类CommonBusiness注入logger
   */
  @Override
  protected Logger getLogger() {
    return logger;
  }

}
