package me.tongzhuangzhuang.business.entity;

import me.tongzhuangzhuang.support.dao.BaseEntity;

/**
 * 
 * @generated by Code Generator v0.1
 * @date Tue May 31 16:05:13 CST 2016
 */
public class TPrdCategory extends BaseEntity<String> {

  /**
   * @field id
   */
  private String id;

  /**
   * @field categoryName
   */
  private String categoryName;

  /**
   * @field categoryType
   */
  private Byte categoryType;

  /**
   * @field categoryRate
   */
  private Object categoryRate;

  /**
   * @field deleteFlag
   */
  private Byte deleteFlag;

  /**
   * @return id
   */
  public String getId() {
    return id;
  }

  /**
   * @param id
   */
  public void setId(String id) {
    this.id = id;
  }

  /**
   * @return categoryName
   */
  public String getCategoryName() {
    return categoryName;
  }

  /**
   * @param categoryName
   */
  public void setCategoryName(String categoryName) {
    this.categoryName = categoryName;
  }

  /**
   * @return categoryType
   */
  public Byte getCategoryType() {
    return categoryType;
  }

  /**
   * @param categoryType
   */
  public void setCategoryType(Byte categoryType) {
    this.categoryType = categoryType;
  }

  /**
   * @return categoryRate
   */
  public Object getCategoryRate() {
    return categoryRate;
  }

  /**
   * @param categoryRate
   */
  public void setCategoryRate(Object categoryRate) {
    this.categoryRate = categoryRate;
  }

  /**
   * @return deleteFlag
   */
  public Byte getDeleteFlag() {
    return deleteFlag;
  }

  /**
   * @param deleteFlag
   */
  public void setDeleteFlag(Byte deleteFlag) {
    this.deleteFlag = deleteFlag;
  }
}
