package me.tongzhuangzhuang.business.dao;

import me.tongzhuangzhuang.business.entity.TCustCustomerBase;
import me.tongzhuangzhuang.support.dao.BaseDao;

/**
 * 
 * @generated by Code Generator v0.1
 * @date Tue May 31 16:05:12 CST 2016
 */
public interface CustCustomerBaseDao extends BaseDao<TCustCustomerBase> {

}
