package me.tongzhuangzhuang.business.dao;

import me.tongzhuangzhuang.business.entity.TPrdCategory;
import me.tongzhuangzhuang.support.dao.BaseDao;

/**
 * 
 * @generated by Code Generator v0.1
 * @date Tue May 31 16:05:13 CST 2016
 */
public interface PrdCategoryDao extends BaseDao<TPrdCategory> {

}
