package me.tongzhuangzhuang.business.service.impl;

import me.tongzhuangzhuang.business.biz.CustCustomerBaseBusiness;
import me.tongzhuangzhuang.business.service.CustCustomerBaseService;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;

/**
 * 
 * @generated by Code Generator v0.1
 * @Tue May 31 16:05:12 CST 2016
 */
public class CustCustomerBaseServiceImpl implements CustCustomerBaseService {

  @Autowired
  private CustCustomerBaseBusiness custCustomerBaseBusiness;

  private static Logger logger = LoggerFactory.getLogger(CustCustomerBaseServiceImpl.class);

}
