package me.tongzhuangzhuang.business.service.impl;

import me.tongzhuangzhuang.business.biz.PrdCategoryBusiness;
import me.tongzhuangzhuang.business.service.PrdCategoryService;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;

/**
 * 
 * @generated by Code Generator v0.1
 * @Tue May 31 16:05:13 CST 2016
 */
public class PrdCategoryServiceImpl implements PrdCategoryService {

  @Autowired
  private PrdCategoryBusiness prdCategoryBusiness;

  private static Logger logger = LoggerFactory.getLogger(PrdCategoryServiceImpl.class);

}
